name: NSFW Subreddits Retrieval and Sort
on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  push:
    branches:
      - main
jobs:
  retrieve-nsfw-subreddits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    
      - name: Run reddit.py
        run: |
          pip3 install -r requirements.txt
          python3 reddit.py
    
      - name: List files after reddit.py
        run: git status
    
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase
            git stash pop
            git commit -m "Retrieve NSFW Subreddits" -a
            git push
          fi
