name: Phishing Domain Retrieval
on:
  schedule:
    # Run monthly on the first day of the month at 00:00 UTC
    - cron: '0 0 1 * *'

jobs:
  retrieve-phishing-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    
      - name: Run phishing.py
        run: |
          pip3 install -r requirements.txt
          python3 phishing.py
    
      - name: List files after phishing
        run: git status

      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase
            git stash pop
            git commit -m "Retrieve Phishing Domains" -a
            git push
          fi
