name: Sort and Commit
on:
  schedule:
    - cron: '5 0 * * *' # Run every day at 00:05 (5 minutes after midnight)
  push:
    branches:
      - main

jobs:
  sort-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    
      - name: Run sort.py
        run: python3 sort.py
    
      - name: List files after sort
        run: git status
    
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase
            git stash pop
            git add .
            git commit -m "Sort and update links"
            git push
          fi
