name: Sort and Filter
on:
  workflow_run:
    workflows:
      - Phishing Domain Retrieval
    types:
      - completed

jobs:
  sort-and-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Run rsfunceble
        run: |
          cargo install rsfunceble
          rsfunceble -i data/nsfw/nsfw_sites.txt -o data/nsfw/nsfw_sites -c 1000 -v
          rsfunceble -i data/phishing/phishing_sites.txt -o data/phishing/phishing_sites -c 1000 -v
          rsfunceble -i data/suspicious/malware_sites.txt -o data/suspicious/malware_sites -c 1000 -v
        
      - name: Run sort.py
        run: python3 sort.py
    
      - name: List files after sort
        run: git status
    
      - name: Commit and Push
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Sort and update links"
            for i in {1..5}; do
              git push && break || (echo "Retrying push... ($i)" && sleep 5)
            done
          fi
