name: Sort File Contents
on:
  push:
    branches:
      - main
jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run sort.py
        run: python3 sort.py

      - name: List files after sort
        run: git status

      - name: Commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Sort Links"
          git push
