name: Sort File Contents
on:
  push:
    branches:
      - main
jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run sort.py
        run: python3 sort.py

      - name: List files after sort
        run: git status

      - name: Commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -am "Sort files"
            git pull --rebase --strategy-option theirs origin sort-files
            git push --set-upstream origin sort-files
          fi
